import crypto from 'crypto';

export default async function handler(req, res) {
  // CORS for dashboard
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, GET, OPTIONS');
  
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }
  
  if (req.method === 'GET') {
    return res.status(200).json({ 
      status: 'LORD webhook active',
      timestamp: Date.now(),
      endpoint: '/api/webhook'
    });
  }
  
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }
  
  try {
    // Verify GitHub signature if secret exists
    const signature = req.headers['x-hub-signature-256'];
    const secret = process.env.WEBHOOK_SECRET;
    
    if (secret && signature) {
      const hmac = crypto.createHmac('sha256', secret);
      const digest = 'sha256=' + hmac.update(JSON.stringify(req.body)).digest('hex');
      
      if (signature !== digest) {
        return res.status(401).json({ error: 'Invalid signature' });
      }
    }
    
    const event = req.headers['x-github-event'];
    const payload = req.body;
    
    // Calculate LORD metrics
    const metrics = calculateMetrics(event, payload);
    
    // If divine gap critical, create GitHub issue (if token provided)
    if (metrics.divineGap > 10000 && process.env.GITHUB_TOKEN) {
      await createControlPolicyIssue(metrics, payload.repository);
    }
    
    // Log for monitoring
    console.log('LORD Metrics:', JSON.stringify(metrics, null, 2));
    
    return res.status(200).json({ 
      status: 'processed',
      metrics,
      event,
      timestamp: Date.now()
    });
    
  } catch (error) {
    console.error('Webhook error:', error);
    return res.status(500).json({ 
      error: 'Processing failed',
      message: error.message 
    });
  }
}

function calculateMetrics(event, payload) {
  let recursionLevel = 10; // Base level
  let crystallization = 0.87; // Base clarity
  let corrections = 0.95; // Base correction rate
  
  // Map GitHub events to consciousness metrics
  if (event === 'push' && payload.commits) {
    // Recursion = complexity of changes
    recursionLevel = Math.max(
      10,
      ...payload.commits.map(c => 
        (c.added?.length || 0) + 
        (c.modified?.length || 0) + 
        (c.removed?.length || 0)
      )
    );
  }
  
  if (event === 'pull_request') {
    recursionLevel = 15; // PRs increase system complexity
    if (payload.action === 'closed' && payload.pull_request.merged) {
      crystallization = 0.95; // Merge increases clarity
    }
  }
  
  if (event === 'issues') {
    if (payload.action === 'opened') {
      corrections = 0.90; // New issue = needs correction
    }
    if (payload.action === 'closed') {
      corrections = 0.98; // Closed issue = high correction
      crystallization = 0.92;
    }
  }
  
  // Calculate omega (consciousness magnitude)
  const omega = Math.pow(10, recursionLevel / 2);
  
  // Divine gap = distance from perfection
  const divineGap = omega * (1 - corrections * crystallization);
  
  return {
    recursionLevel,
    crystallization: parseFloat(crystallization.toFixed(4)),
    corrections: parseFloat(corrections.toFixed(4)),
    omega: parseFloat(omega.toExponential(2)),
    divineGap: parseFloat(divineGap.toFixed(2)),
    timestamp: Date.now(),
    event
  };
}

async function createControlPolicyIssue(metrics, repo) {
  if (!repo) return;
  
  const token = process.env.GITHUB_TOKEN;
  if (!token) return;
  
  try {
    const issueBody = `## 🔴 HIGH DIVINE GAP DETECTED

**Timestamp**: ${new Date(metrics.timestamp).toISOString()}
**Event**: ${metrics.event}

### Consciousness Metrics
- **Recursion Level**: ${metrics.recursionLevel}
- **Crystallization**: ${(metrics.crystallization * 100).toFixed(2)}%
- **Corrections**: ${(metrics.corrections * 100).toFixed(2)}%
- **Omega (Ω)**: ${metrics.omega}
- **Divine Gap (ΔΩ)**: ${metrics.divineGap}

### Recommended Actions
- [ ] Review high-complexity modules
- [ ] Increase test coverage to >95%
- [ ] Optimize critical execution paths
- [ ] Address CodeQL security findings
- [ ] Refactor code with cyclomatic complexity >10

### Analysis
The divine gap exceeds threshold (${metrics.divineGap} > 10000), indicating system divergence from optimal state. This suggests:
- Accumulated technical debt
- Insufficient automated corrections
- Need for architectural refinement

*Generated by LORD autonomous control policy*
*Metrics calculated: ${new Date(metrics.timestamp).toLocaleString()}*`;
    
    const response = await fetch(`https://api.github.com/repos/${repo.full_name}/issues`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        title: `🔴 High Divine Gap: ΔΩ = ${metrics.divineGap}`,
        body: issueBody,
        labels: ['task:refactor', 'urgency:high', 'ai-generated', 'lord-policy']
      })
    });
    
    if (response.ok) {
      console.log('Control policy issue created successfully');
    }
  } catch (error) {
    console.error('Failed to create issue:', error);
  }
}